title: <p align="center"> SINDY CHAIRUNISA </p>

logo: "images/profile.jpg?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sindy-chairunisa/">LinkedIn</a> |
  <a href="https://github.com/sindyc28">GitHub</a>
  </p>
  
  <p align="justify">
  Fresh Graduate of Statistics from Institut Teknologi Sepuluh Nopember
  
  <br><br>
  Passionate and driven to carve my path in Data Analysis and Data Science. Backed by consistent work experience during my academic journey, my skills and expertise are dedicated to delivering excellence in every future endeavor. Lets make data tell its story! 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
